#  Copyright (c) Juniper Networks, Inc., 2025-2025.
#  All rights reserved.
#  SPDX-License-Identifier: MIT

name: Checks

on:
  push:

jobs:
  license-file-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read me if there are errors!
        run: tail -1 publisher_guide/license.md
      - name: Check license headers
        run: ./.ci/scripts/check_license.sh
  signing-key-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read me if there are errors!
        run: tail -1 LICENSE
      - name: Import signing key
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Sign test file
        run: |
          f=$(mktemp)
          dd if=/dev/urandom of=$f count=1
          gpg --default-key ${{ steps.import_gpg.outputs.fingerprint }} --passphrase-fd 0 --pinentry-mode=loopback --sign $f <<< $PASSPHRASE
          ls -l $f*
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
  tofu-permitted-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read me if there are errors!
        run: tail -1 publisher_guide/tofu-guidelines.md
      - name: Ensure files in pack/tofu look like *.tf
        run: if ls -a pack/tofu | egrep -v '^\.{1,2}$|\.tf$'; then echo "files not ending with '.tf' found in pack/tofu/"; exit 1; fi
  tofu-fmt-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read me if there are errors!
        run: tail -1 publisher_guide/tofu-guidelines.md
      - name: OpenTofu - Setup Tofu
        uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1.0.5
        with:
          tofu_version: 1.9.0
      - name: run tofu fmt
        run: ./.ci/scripts/tofu_fmt.sh
